In [1]:
import pandas as pd
import numpy as np

from sklearn.linear_model import LinearRegression

In [3]:
url = "https://raw.githubusercontent.com/campusx-official/100-days-of-machine-learning/main/day40-iterative-imputer/50_Startups.csv"

# Importing the CSV file
df = np.round(pd.read_csv(url)[['R&D Spend','Administration','Marketing Spend','Profit']]/10000)

In [4]:
df = df.sample(5)
df

,R&D Spend,Administration,Marketing Spend,Profit
22,7.0,12.0,30.0,11.0
39,4.0,8.0,17.0,8.0
35,5.0,9.0,21.0,10.0
19,9.0,15.0,0.0,12.0
29,7.0,15.0,11.0,10.0


In [5]:
df = df.iloc[:,0:-1]
df

,R&D Spend,Administration,Marketing Spend
22,7.0,12.0,30.0
39,4.0,8.0,17.0
35,5.0,9.0,21.0
19,9.0,15.0,0.0
29,7.0,15.0,11.0


In [7]:
df.iloc[1,0] = np.nan
df.iloc[3,1] = np.nan
df.iloc[-1,-1] = np.nan
df.head()

,R&D Spend,Administration,Marketing Spend
22,7.0,12.0,30.0
39,NaN,8.0,17.0
35,5.0,9.0,21.0
19,9.0,NaN,0.0
29,7.0,15.0,NaN


In [8]:
# Step 1 - Impute all missing values with mean of respective col

df0 = pd.DataFrame()

df0['R&D Spend'] = df['R&D Spend'].fillna(df['R&D Spend'].mean())
df0['Administration'] = df['Administration'].fillna(df['Administration'].mean())
df0['Marketing Spend'] = df['Marketing Spend'].fillna(df['Marketing Spend'].mean())
# 0th Iteration
df0

,R&D Spend,Administration,Marketing Spend
22,7.0,12.0,30.0
39,7.0,8.0,17.0
35,5.0,9.0,21.0
19,9.0,11.0,0.0
29,7.0,15.0,17.0


In [10]:
# Remove the col1 imputed value
df1 = df0.copy()

df1.iloc[1,0] = np.nan

df1

,R&D Spend,Administration,Marketing Spend
22,7.0,12.0,30.0
39,NaN,8.0,17.0
35,5.0,9.0,21.0
19,9.0,11.0,0.0
29,7.0,15.0,17.0


In [11]:
# Use first 3 rows to build a model and use the last for prediction

X = df1.iloc[[0,2,3,4],1:3]
X

,Administration,Marketing Spend
22,12.0,30.0
35,9.0,21.0
19,11.0,0.0
29,15.0,17.0


In [12]:
y = df1.iloc[[0,2,3,4],0]
y

22    7.0
35    5.0
19    9.0
29    7.0
Name: R&D Spend, dtype: float64

In [13]:

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df1.iloc[1,1:].values.reshape(1,2))

d:\CODING\MACHINE LEARNING\.venv\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([6.10888575])

In [14]:
df1.iloc[1,0] = 6.10888575
df1

,R&D Spend,Administration,Marketing Spend
22,7.000000,12.0,30.0
39,6.108886,8.0,17.0
35,5.000000,9.0,21.0
19,9.000000,11.0,0.0
29,7.000000,15.0,17.0


In [16]:
# Remove the col2 imputed value

df1.iloc[3,1] = np.nan

df1

,R&D Spend,Administration,Marketing Spend
22,7.000000,12.0,30.0
39,6.108886,8.0,17.0
35,5.000000,9.0,21.0
19,9.000000,NaN,0.0
29,7.000000,15.0,17.0


In [17]:
# Use last 3 rows to build a model and use the first for prediction
X = df1.iloc[[0,1,2,4],[0,2]]
X

,R&D Spend,Marketing Spend
22,7.000000,30.0
39,6.108886,17.0
35,5.000000,21.0
29,7.000000,17.0


In [18]:
y = df1.iloc[[0,1,2,4],1]
y

22    12.0
39     8.0
35     9.0
29    15.0
Name: Administration, dtype: float64

In [19]:
lr = LinearRegression()
lr.fit(X,y)
lr.predict(df1.iloc[3,[0,2]].values.reshape(1,2))

d:\CODING\MACHINE LEARNING\.venv\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([19.06475122])

In [20]:
df1.iloc[3,1] = 19.06475122
df1

,R&D Spend,Administration,Marketing Spend
22,7.000000,12.000000,30.0
39,6.108886,8.000000,17.0
35,5.000000,9.000000,21.0
19,9.000000,19.064751,0.0
29,7.000000,15.000000,17.0


In [22]:
# Remove the col3 imputed value
df1.iloc[4,-1] = np.nan

df1

,R&D Spend,Administration,Marketing Spend
22,7.000000,12.000000,30.0
39,6.108886,8.000000,17.0
35,5.000000,9.000000,21.0
19,9.000000,19.064751,0.0
29,7.000000,15.000000,NaN


In [23]:
# Use last 3 rows to build a model and use the first for prediction
X = df1.iloc[0:4,0:2]
X

,R&D Spend,Administration
22,7.000000,12.000000
39,6.108886,8.000000
35,5.000000,9.000000
19,9.000000,19.064751


In [24]:
y = df1.iloc[0:4,-1]
y

22    30.0
39    17.0
35    21.0
19     0.0
Name: Marketing Spend, dtype: float64

In [25]:
lr = LinearRegression()
lr.fit(X,y)
lr.predict(df1.iloc[4,0:2].values.reshape(1,2))

d:\CODING\MACHINE LEARNING\.venv\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([11.86436955])

In [26]:
df1.iloc[4,-1] = 11.86436955
# After 1st Iteration
df1

,R&D Spend,Administration,Marketing Spend
22,7.000000,12.000000,30.00000
39,6.108886,8.000000,17.00000
35,5.000000,9.000000,21.00000
19,9.000000,19.064751,0.00000
29,7.000000,15.000000,11.86437


In [27]:
# Subtract 0th iteration from 1st iteration

df1 - df0

,R&D Spend,Administration,Marketing Spend
22,0.000000,0.000000,0.00000
39,-0.891114,0.000000,0.00000
35,0.000000,0.000000,0.00000
19,0.000000,8.064751,0.00000
29,0.000000,0.000000,-5.13563


In [29]:
df2 = df1.copy()

df2.iloc[1,0] = np.nan

df2

,R&D Spend,Administration,Marketing Spend
22,7.0,12.000000,30.00000
39,NaN,8.000000,17.00000
35,5.0,9.000000,21.00000
19,9.0,19.064751,0.00000
29,7.0,15.000000,11.86437


In [30]:
X = df2.iloc[[0,2,3,4],1:3]
y = df2.iloc[[0,2,3,4],0]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df2.iloc[1,1:].values.reshape(1,2))

d:\CODING\MACHINE LEARNING\.venv\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([4.17335709])

In [31]:
df2.iloc[1,0] = 4.17335709
df2.iloc[3,1] = np.nan
X = df2.iloc[[0,1,2,4],[0,2]]
y = df2.iloc[[0,1,2,4],1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df2.iloc[3,[0,2]].values.reshape(1,2))

d:\CODING\MACHINE LEARNING\.venv\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([21.3713218])

In [32]:
df2.iloc[3,1] = 21.3713218
df2.iloc[4,-1] = np.nan

X = df2.iloc[0:4,0:2]
y = df2.iloc[0:4,-1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df2.iloc[4,0:2].values.reshape(1,2))

d:\CODING\MACHINE LEARNING\.venv\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([11.87540753])

In [33]:
df2.iloc[4,-1] = 11.87540753
df2

,R&D Spend,Administration,Marketing Spend
22,7.000000,12.000000,30.000000
39,4.173357,8.000000,17.000000
35,5.000000,9.000000,21.000000
19,9.000000,21.371322,0.000000
29,7.000000,15.000000,11.875408


In [34]:
df2 - df1

,R&D Spend,Administration,Marketing Spend
22,0.000000,0.000000,0.000000
39,-1.935529,0.000000,0.000000
35,0.000000,0.000000,0.000000
19,0.000000,2.306571,0.000000
29,0.000000,0.000000,0.011038


REPEAT TILL DIFFERENCE IS 0 OR NEAR 0


In [37]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.linear_model import LinearRegression

mice_imputer = IterativeImputer(estimator=LinearRegression(), max_iter=10, random_state=42)

imputed_array = mice_imputer.fit_transform(df)
df_imputed = pd.DataFrame(imputed_array, columns=df.columns)

print("\nMissing values after MICE imputation:")
print(df_imputed.isnull().sum())


Missing values after MICE imputation:
R&D Spend          0
Administration     0
Marketing Spend    0
dtype: int64
